# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Publish Maven artifact (.jar) to Github Packages Registry
# Deploy Maven artifact to Azure Web App service
name: Deploy & Publish

on:
  workflow_run:
    workflows: ["Build & Test"]
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup java environment
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      # Build artifact
      - name: Build with Maven
        run: mvn clean install
      # Upload artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
  # Deploy to Azure app service
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'puff-course-management'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ef5115cc7ff4b769924450f015f7ab6 }}
          package: '*.jar'
  # Publish maven artifact to Github
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Publish to Github Packages
        run: mvn -B -U --no-transfer-progress -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 