name: Validate
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Validate package version
        run: |
          VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $VERSION =~ "SNAPSHOT" ]]; then 
            exit 0
          else
            echo "pom.xml version must contain 'SNAPSHOT'"
            exit 1
          fi
      - name: Validate source file formatting
        run: mvn -B -U --no-transfer-progress --file pom.xml formatter:validate